
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boottest?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
mybatis:
  type-aliases-package: com.ssmt1.pojo
server:
  port: 8080